# Site settings
author: Robert Leduc
title: Why I decided to study Software Engineering
header-img: img/home-bg.png
email: rleduc34@gmail.com
copyright_name: Robert Leduc
description: > # this means to ignore newlines until "baseurl:"
  “Why did you decide to study Software Engineering?”
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rleduc34

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
